[metadata]
name = "my-man"
description = "Browse and preview system manual pages"
requirements = [ "apropos", "man",]

[source]
command = "apropos . | awk '{print $1}' | sed -E 's/\\([0-9a-z]+\\)//'"

[preview]
command = "man '{0}'"

[keybindings]
enter = "actions:open"


[preview.env]
MANWIDTH = "80"

[actions.open]
description = "Open the selected man page in the system pager"
command = "man '{0}'"
mode = "execute"

[ui.preview_panel]
header = "{0}"

