source-file $XDG_CONFIG_HOME/tmux/tmux.reset.conf
set-option -g terminal-overrides ',xterm-256color:RGB'

# --- BASE SETTINGS
set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-border-style 'fg=blue,bg=default'
set -g mouse on 


# --- PLUGINS
# Change the path so that tpm installs plugins outside of the config dir and they are not pushed to git.
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'
# Plugins in use
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-yank'

bind-key "o" display-popup -E -w 75% -h 75% -d '#{pane_current_path}' -T 'Sesh' tv sesh

# --- THEME SETTINGS
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
bind-key b set-option status


# --- PLUGIN SETTINGS
# Floax
set -g @floax-width '75%'
set -g @floax-height '75%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'


run '~/.tmux/plugins/tpm/tpm'


